# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetrievedBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False, help_text='Использован ли бонус командой')),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieved', to='map.AbstractBonus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='retrievedbonus',
            unique_together=set([('user', 'bonus')]),
        ),
    ]
