# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ejudge_user_id',
            field=models.PositiveIntegerField(default=0, help_text='Идентификатор пользователя в еджадже'),
            preserve_default=False,
        ),
    ]
