# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userinfo_ejudge_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ejudge_user_id',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Идентификатор пользователя в еджадже'),
        ),
    ]
